workflows:
  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m1
    environment:
      node: latest
      groups:
        - apple_credentials
    scripts:
      - name: Install Dependencies
        script: |
          corepack enable
          corepack prepare pnpm@latest --activate
          pnpm install
      - name: Build web assets
        script: |
          pnpm run app:build
      - name: Sync Capacitor iOS
        script: |
          npx cap sync ios
    artifacts:
      - "**/ios/App/App/build/**/*.ipa"



































