workflows:
  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m1
    environment:
      node: latest
      groups:
        - apple_credentials
    scripts:
      - name: Install Dependencies
        script: |
          # إزالة أي تداخل محتمل في المجلد الرئيسي لمنع اعتراض Yarn
          rm -f /Users/builder/package.json /Users/builder/yarn.lock
          cd /Users/builder/clone
          corepack enable
          yarn install
      - name: Build web assets
        script: |
          cd /Users/builder/clone
          yarn run app:build
      - name: Sync Capacitor iOS
        script: |
          cd /Users/builder/clone
          npx cap sync ios
    artifacts:
      - "**/ios/App/App/build/**/*.ipa"





































